debug: false
management.endpoints.web.exposure.include: "*"

logging:
  level:
    com.thc.sprapi: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

spring:
  thymeleaf:
    cache: false
  devtools:
    restart:
      enabled: false
  profiles:
    include: login, database

sql.init.mode: always
springdoc:
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha

google:
  login:
    client_id: 562074838314-72fd9hvdaqbh3a8u13p22estnl0ktova.apps.googleusercontent.com