spring:
  datasource:
    url: jdbc:mysql://localhost:3306/scsprapi?characterEncoding=UTF-8&serverTimezone=UTC
    username: namoo
    password: shk121!@
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate.ddl-auto: update # create: ???? build ?? ?? ???? ???? ??, update: ??? ???? ?????? ??
    show-sql: true
    properties:
      hibernate.format_sql: true # SQL?? log? ?? ? , none
      hibernate.default_batch_fetch_size: 100
      hibernate.jdbc.time_zone: Asia/Seoul