external:
  jwt:
    tokenSecretKey: cfc6f8968e16e357e2a588674174bc2ca34b538e9f759d081d48721fd0aa1f626188fca140ca58a5b88d6e98b3302c52f49f7fa1dc06924c34ecd45b31ba675e
    tokenPrefix: Bearer/u0020
    accessKey: Authorization
    accessTokenExpirationTime: 300000
    refreshKey: RefreshToken
    refreshTokenExpirationTime: 900000 # 15분
    # 1000 * 60 * 60 * 24 * 7 = 604800000 1주일
    # 1000 * 60 * 30 = 1800000 30분

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 461546540519-6ef9kgjibtbb65d24810c7avs5tagf4i.apps.googleusercontent.com
            client-secret: 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
            #            redirect-uri: "http://localhost:8080/login/oauth2/code/google"
            scope: profile,email
          naver:
            client-id: OJba_8l8Q5dQAPDdoSLV
            client-secret: 0gIUm5qhnJ
            redirect-uri: http://localhost:8080/api/user/naver
            authorization-grant-type: authorization_code
            scope: name, email, profile_image
            client-name: Naver
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response